// angular-app/src/app/shared/layout/layout.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-layout',
  imports: [RouterLink, RouterLinkActive, RouterOutlet],
  templateUrl: './layout.html',
  styleUrl: './layout.scss',
})
export class AppLayout {
  protected readonly links = [
    { path: '/', label: 'Accueil', exact: true },
    { path: '/counter', label: 'Compteur', exact: false },
    { path: '/signup', label: 'Inscription', exact: false },
    { path: '/todos', label: 'TodoList', exact: false },
  ];
}

// react-app/src/components/Layout/Layout.tsx
import clsx from "clsx";
import { NavLink, Outlet } from "react-router-dom";
import styles from "./Layout.module.scss";

const links = [
  { to: "/", label: "Accueil", end: true },
  { to: "/counter", label: "Compteur", end: false },
  { to: "/signup", label: "Inscription", end: false },
  { to: "/todos", label: "TodoList", end: false },
];

export function Layout() {
  return (
    <div className={styles.shell}>
      <header className={styles.header}>
        <div className={styles.inner}>
          <span className={styles.brand}>React 19</span>
          <nav className={styles.nav}>
            {links.map(({ to, label, end }) => (
              <NavLink
                key={to}
                to={to}
                end={end}
                className={({ isActive }) =>
                  clsx(styles.link, isActive && styles.linkActive)
                }
              >
                {label}
              </NavLink>
            ))}
          </nav>
        </div>
      </header>

      <main className={styles.main}>
        <Outlet />
      </main>
    </div>
  );
}
